#!/bin/bash
# get-keys.sh — Retrieve keys and configure .env for the MAF Workshop
# Usage: ./get-keys.sh --resource-group <name>

set -e

RESOURCE_GROUP=""
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --resource-group|-g) RESOURCE_GROUP="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [ -z "$RESOURCE_GROUP" ]; then
    echo "❌ Error: --resource-group is required"
    echo "Usage: ./get-keys.sh --resource-group <name>"
    exit 1
fi

echo "🔑 Retrieving keys for MAF Workshop"
echo "   Resource Group: $RESOURCE_GROUP"
echo ""

# Get the AI Foundry project endpoint
echo "📡 Finding AI Foundry project endpoint..."
PROJECT_ENDPOINT=$(az cognitiveservices account show \
    --resource-group "$RESOURCE_GROUP" \
    --name "maf-lab-ai" \
    --query "properties.endpoint" \
    --output tsv 2>/dev/null)

if [ -z "$PROJECT_ENDPOINT" ]; then
    echo "   ⚠️  Could not auto-detect endpoint. Trying alternative..."
    PROJECT_ENDPOINT=$(az cognitiveservices account list \
        --resource-group "$RESOURCE_GROUP" \
        --query "[?kind=='AIServices'].properties.endpoint | [0]" \
        --output tsv)
fi

echo "   ✅ Endpoint: $PROJECT_ENDPOINT"

# Get current user's tenant ID
echo "🏢 Getting tenant ID..."
TENANT_ID=$(az account show --query "tenantId" --output tsv)
echo "   ✅ Tenant: $TENANT_ID"

# Get current user's object ID for role assignment
echo "👤 Getting current user..."
USER_OBJECT_ID=$(az ad signed-in-user show --query "id" --output tsv)
USER_UPN=$(az ad signed-in-user show --query "userPrincipalName" --output tsv)
echo "   ✅ User: $USER_UPN"

# Assign Azure AI Developer role
echo "🔐 Assigning 'Azure AI Developer' role..."
az role assignment create \
    --assignee "$USER_OBJECT_ID" \
    --role "Azure AI Developer" \
    --scope "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/$RESOURCE_GROUP" \
    --output none 2>/dev/null || echo "   ⚠️  Role may already be assigned"
echo "   ✅ Role assigned"

# Assign Cognitive Services User role
echo "🔐 Assigning 'Cognitive Services User' role..."
az role assignment create \
    --assignee "$USER_OBJECT_ID" \
    --role "Cognitive Services User" \
    --scope "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/$RESOURCE_GROUP" \
    --output none 2>/dev/null || echo "   ⚠️  Role may already be assigned"
echo "   ✅ Role assigned"

# Write .env file
echo ""
echo "📝 Writing .env file..."
cat > "$ENV_FILE" << EOF
# Azure AI Foundry Configuration (auto-generated by get-keys.sh)
AZURE_AI_PROJECT_ENDPOINT="$PROJECT_ENDPOINT"
AZURE_AI_MODEL_DEPLOYMENT_NAME="gpt-4o"
AZURE_TENANT_ID="$TENANT_ID"
EOF

echo "   ✅ Written to: $ENV_FILE"
echo ""
echo "🎉 Setup complete! You can now run the workshop notebooks."
echo ""
echo "   To verify: Open challenge-0/verify-setup.ipynb and run all cells"
